#[derive(
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Enum,
)]
pub enum AgentToolName {
    CreateNote,
    RecordMemory,
    UpgradeThinking,
    UseSkill,
    Ask,
    ScheduleTask,
    CancelScheduledTask,
    ListScheduledTasks,
    ListConversations,
    SearchConversations,
    PlayEpisode,
    PausePlayback,
    SetPlaybackRate,
    SetSleepTimer,
    SearchEpisodes,
    QueryTranscripts,
    PerplexitySearch,
    SummarizeEpisode,
    FindSimilarEpisodes,
    MarkEpisodePlayed,
    MarkEpisodeUnplayed,
    DownloadEpisode,
    RequestTranscription,
    RefreshFeed,
    ListSubscriptions,
    ListPodcasts,
    ListCategories,
    ChangePodcastCategory,
    ListEpisodes,
    ListInProgress,
    ListRecentUnplayed,
    CreateClip,
    DownloadAndTranscribe,
    GenerateTtsEpisode,
    ConfigureAgentVoice,
    ListAvailableVoices,
    SearchPodcastDirectory,
    SubscribePodcast,
    DeletePodcast,
    IngestYoutubeVideo,
    SearchYoutube,
    CreatePodcast,
    UpdatePodcast,
    DeleteMyPodcast,
    ListMyPodcasts,
    GeneratePodcastArtwork,
}

pub const ALL_AGENT_TOOL_NAMES: &[(&str, AgentToolName)] = &[
    ("create_note", AgentToolName::CreateNote),
    ("record_memory", AgentToolName::RecordMemory),
    ("upgrade_thinking", AgentToolName::UpgradeThinking),
    ("use_skill", AgentToolName::UseSkill),
    ("ask", AgentToolName::Ask),
    ("schedule_task", AgentToolName::ScheduleTask),
    ("cancel_scheduled_task", AgentToolName::CancelScheduledTask),
    ("list_scheduled_tasks", AgentToolName::ListScheduledTasks),
    ("list_conversations", AgentToolName::ListConversations),
    ("search_conversations", AgentToolName::SearchConversations),
    ("play_episode", AgentToolName::PlayEpisode),
    ("pause_playback", AgentToolName::PausePlayback),
    ("set_playback_rate", AgentToolName::SetPlaybackRate),
    ("set_sleep_timer", AgentToolName::SetSleepTimer),
    ("search_episodes", AgentToolName::SearchEpisodes),
    ("query_transcripts", AgentToolName::QueryTranscripts),
    ("perplexity_search", AgentToolName::PerplexitySearch),
    ("summarize_episode", AgentToolName::SummarizeEpisode),
    ("find_similar_episodes", AgentToolName::FindSimilarEpisodes),
    ("mark_episode_played", AgentToolName::MarkEpisodePlayed),
    ("mark_episode_unplayed", AgentToolName::MarkEpisodeUnplayed),
    ("download_episode", AgentToolName::DownloadEpisode),
    ("request_transcription", AgentToolName::RequestTranscription),
    ("refresh_feed", AgentToolName::RefreshFeed),
    ("list_subscriptions", AgentToolName::ListSubscriptions),
    ("list_podcasts", AgentToolName::ListPodcasts),
    ("list_categories", AgentToolName::ListCategories),
    (
        "change_podcast_category",
        AgentToolName::ChangePodcastCategory,
    ),
    ("list_episodes", AgentToolName::ListEpisodes),
    ("list_in_progress", AgentToolName::ListInProgress),
    ("list_recent_unplayed", AgentToolName::ListRecentUnplayed),
    ("create_clip", AgentToolName::CreateClip),
    (
        "download_and_transcribe",
        AgentToolName::DownloadAndTranscribe,
    ),
    ("generate_tts_episode", AgentToolName::GenerateTtsEpisode),
    ("configure_agent_voice", AgentToolName::ConfigureAgentVoice),
    ("list_available_voices", AgentToolName::ListAvailableVoices),
    (
        "search_podcast_directory",
        AgentToolName::SearchPodcastDirectory,
    ),
    ("subscribe_podcast", AgentToolName::SubscribePodcast),
    ("delete_podcast", AgentToolName::DeletePodcast),
    ("ingest_youtube_video", AgentToolName::IngestYoutubeVideo),
    ("search_youtube", AgentToolName::SearchYoutube),
    ("create_podcast", AgentToolName::CreatePodcast),
    ("update_podcast", AgentToolName::UpdatePodcast),
    ("delete_my_podcast", AgentToolName::DeleteMyPodcast),
    ("list_my_podcasts", AgentToolName::ListMyPodcasts),
    (
        "generate_podcast_artwork",
        AgentToolName::GeneratePodcastArtwork,
    ),
];
