import Foundation
import os.log

// MARK: - AgentGeneratedPodcastService
//
// Manages the "Agent Generated" virtual `Podcast` and its on-disk episode
// audio files.
//
// The podcast uses the sentinel feed URL `agent-generated://podcast` and
// `kind: .synthetic` so it is excluded from OPML export, feed-refresh
// scheduling, and automatic download candidate reporting. Callers
// branch on `Podcast.kind == .synthetic` rather than comparing URL strings.
//
// The user is NOT auto-subscribed to this podcast — synthetic shows have a
// `Podcast` row but no `PodcastSubscription`. Episodes still appear in the
// library through the normal episode list; the show simply doesn't show up
// in the user's followed-podcasts list.
//
// Audio files live under:
//   Application Support / podcastr / agent-episodes / <episodeID>.m4a
//
// Each call to `publishEpisode` creates a new `Episode` with a `file://`
// `enclosureURL` pointing at the stitched m4a. This is source media, not a
// downloaded-artifact fact; the player reads it through AudioEngine's native
// local-file path.

struct AgentGeneratedPodcastService: Sendable {

    private static let logger = Logger.app("AgentGeneratedPodcastService")

    // MARK: - Sentinel

    /// Read-only legacy sentinel imported as a feedless synthetic row by Rust.
    static let sentinelFeedURL = URL(string: "agent-generated://podcast")!
    static let defaultPodcastID = UUID(
        uuidString: "6CB45D63-3C88-5FB5-A7D3-270DB60EF514"
    )!

    // MARK: - Storage

    /// Root directory for agent-generated episode audio files.
    static func audioDirectory() throws -> URL {
        let support = try FileManager.default.url(
            for: .applicationSupportDirectory,
            in: .userDomainMask,
            appropriateFor: nil,
            create: true
        )
        let dir = support
            .appendingPathComponent("podcastr", isDirectory: true)
            .appendingPathComponent("agent-episodes", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    /// Returns the canonical m4a URL for an agent episode by its UUID.
    /// The file need not exist yet — callers write here before calling
    /// `publishEpisode`.
    static func audioFileURL(episodeID: UUID) throws -> URL {
        try audioDirectory().appendingPathComponent("\(episodeID.uuidString).m4a")
    }

    // MARK: - Podcast row management

    /// Returns the imported/default agent-generated show or creates it through
    /// the authoritative Rust library.
    @MainActor
    static func ensurePodcast(in store: AppStateStore) async throws -> Podcast {
        if let existing = store.allPodcasts.first(where: {
            $0.id == defaultPodcastID
                || ($0.kind == .synthetic
                    && $0.title == "Agent Generated"
                    && $0.author == "Podcast Agent")
        }) {
            return existing
        }
        let podcast = Podcast(
            id: defaultPodcastID,
            kind: .synthetic,
            feedURL: nil,
            title: "Agent Generated",
            author: "Podcast Agent",
            imageURL: nil,
            description: "Episodes generated by your AI agent."
        )
        let stored = try await store.upsertSyntheticPodcastAndWait(podcast)
        logger.info("Created agent-generated podcast \(stored.id, privacy: .public)")
        return stored
    }

    // MARK: - Episode publishing

    /// Registers a finished m4a file as an episode on the agent-generated
    /// podcast and inserts it into `AppStateStore`. The file at `audioURL`
    /// must already exist on disk.
    ///
    /// - Parameter imageURL: Optional artwork to attach directly to the
    ///   episode. The TTS composer passes the source-clip artwork from the
    ///   first snippet chapter so the produced episode has meaningful art
    ///   even though the synthetic podcast itself has none.
    @MainActor
    @discardableResult
    static func publishEpisode(
        title: String,
        description: String,
        audioURL: URL,
        durationSeconds: TimeInterval?,
        imageURL: URL? = nil,
        generationSource: Episode.GenerationSource? = nil,
        targetPodcastID: UUID? = nil,
        in store: AppStateStore
    ) async throws -> Episode {
        let parent: Podcast
        if let targetPodcastID {
            guard let existing = store.podcast(id: targetPodcastID),
                  existing.kind == .synthetic else {
                throw SharedLibraryError.notFound
            }
            parent = existing
        } else {
            parent = try await ensurePodcast(in: store)
        }
        let episode = try await store.upsertExternalEpisodeAndWait(
            podcastID: parent.id,
            feedURL: nil,
            podcastTitle: parent.title,
            audioURL: audioURL,
            title: title,
            description: description,
            publishedAt: Date(),
            enclosureMimeType: "audio/mp4",
            imageURL: imageURL,
            duration: durationSeconds
        )
        store.setEpisodeGenerationSource(episode.id, source: generationSource)
        logger.info("Published agent episode '\(title, privacy: .public)' id=\(episode.id, privacy: .public)")
        return store.episode(id: episode.id) ?? episode
    }
}
