use rusqlite::Connection;

use crate::StorageError;
use crate::schema_introspection::require_columns;

pub(crate) fn validate_model_chapter_workflow_schema(
    connection: &Connection,
) -> Result<(), StorageError> {
    require_columns(
        connection,
        "pod0_model_chapter_workflows",
        &[
            "active_configured_model",
            "attempt",
            "base_artifact_id",
            "base_integrity_digest",
            "cancellation_id",
            "command_id",
            "created_at_ms",
            "deadline_at_ms",
            "desired_configured_model",
            "duration_ms",
            "episode_id",
            "expected_artifact_source_code",
            "expected_selection_revision",
            "failure_code",
            "failure_detail",
            "format_version",
            "generation",
            "issued_revision",
            "maximum_completion_bytes",
            "max_attempts",
            "may_have_submitted",
            "mode",
            "model",
            "not_before_ms",
            "policy_version",
            "provider",
            "provider_operation_id",
            "provider_status",
            "replan_pending",
            "request_fingerprint",
            "request_id",
            "requested_transcript_digest",
            "requested_transcript_version_id",
            "response_format_code",
            "selected_artifact_id",
            "selected_transcript_digest",
            "selected_transcript_version_id",
            "source_version",
            "state",
            "submission_authorized_at_ms",
            "submission_fence_id",
            "system_prompt",
            "updated_at_ms",
            "user_prompt",
            "workflow_revision",
        ],
    )?;
    require_columns(
        connection,
        "pod0_model_chapter_completions",
        &[
            "cached_tokens",
            "completion",
            "completion_digest",
            "completion_tokens",
            "cost_microusd",
            "episode_id",
            "generated_at_ms",
            "generation",
            "model",
            "observed_at_ms",
            "prompt_tokens",
            "provider",
            "provider_operation_id",
            "provider_status",
            "reasoning_tokens",
            "request_id",
            "submission_fence_id",
        ],
    )
}
