use rusqlite::Connection;

use crate::StorageError;
use crate::schema_introspection::require_columns;

pub(crate) fn validate_scheduled_agent_schema(connection: &Connection) -> Result<(), StorageError> {
    require_columns(
        connection,
        "pod0_scheduled_agent_authority",
        &[
            "committed_at_ms",
            "core_revision",
            "singleton",
            "source_generation",
            "state",
        ],
    )?;
    require_columns(
        connection,
        "pod0_scheduled_tasks",
        &[
            "active",
            "created_at_ms",
            "interval_ms",
            "label",
            "last_run_at_ms",
            "model_reference",
            "next_run_at_ms",
            "prompt",
            "prompt_revision",
            "removed_at_ms",
            "task_id",
            "task_revision",
            "updated_at_ms",
        ],
    )?;
    require_columns(
        connection,
        "pod0_scheduled_occurrences",
        &[
            "artifact_id",
            "attempt",
            "attempt_id",
            "created_at_ms",
            "failure_code",
            "failure_detail",
            "failure_retryable",
            "failure_wire_code",
            "model_reference",
            "not_before_ms",
            "occurrence_id",
            "output_digest",
            "prompt",
            "prompt_revision",
            "provider_operation_id",
            "request_id",
            "scheduled_for_ms",
            "stage",
            "task_id",
            "updated_at_ms",
            "workflow_revision",
        ],
    )?;
    require_columns(
        connection,
        "pod0_scheduled_attempts",
        &[
            "attempt",
            "attempt_id",
            "cancellation_id",
            "command_id",
            "created_at_ms",
            "deadline_at_ms",
            "failure_code",
            "failure_detail",
            "failure_retryable",
            "failure_wire_code",
            "issued_revision",
            "last_observation_fingerprint",
            "last_sequence_number",
            "occurrence_id",
            "provider_operation_id",
            "request_id",
            "state",
            "updated_at_ms",
        ],
    )?;
    require_columns(
        connection,
        "pod0_scheduled_completion_evidence",
        &[
            "artifact_id",
            "attempt_id",
            "committed_at_ms",
            "observation_fingerprint",
            "observed_at_ms",
            "occurrence_id",
            "output_digest",
            "output_excerpt",
            "request_id",
            "sequence_number",
            "state",
        ],
    )?;
    require_columns(
        connection,
        "pod0_generated_artifacts",
        &[
            "artifact_id",
            "attempt_id",
            "bounded_excerpt",
            "content_digest",
            "kind",
            "occurrence_id",
            "selected_at_ms",
        ],
    )?;
    require_columns(
        connection,
        "pod0_scheduled_command_receipts",
        &[
            "applied_revision",
            "command_fingerprint",
            "command_id",
            "completed_at_ms",
            "occurrence_id",
            "task_id",
        ],
    )
}

pub(crate) fn validate_scheduled_agent_cutover_schema(
    connection: &Connection,
) -> Result<(), StorageError> {
    require_columns(
        connection,
        "pod0_scheduled_agent_cutover_evidence",
        &[
            "backup_byte_count",
            "backup_digest",
            "committed_at_ms",
            "occurrence_count",
            "singleton",
            "source_fingerprint",
            "source_generation",
            "staged_at_ms",
            "state",
            "task_count",
            "verified_at_ms",
        ],
    )
}
