use rusqlite::Connection;

use crate::StorageError;
use crate::schema_introspection::require_columns;

pub(crate) fn validate_evidence_schema(connection: &Connection) -> Result<(), StorageError> {
    require_columns(
        connection,
        "pod0_transcript_documents",
        &[
            "content_digest",
            "episode_id",
            "podcast_id",
            "provider",
            "segment_count",
            "source_code",
            "source_payload_digest",
            "source_revision",
            "source_wire_code",
            "transcript_version_id",
        ],
    )?;
    require_columns(
        connection,
        "pod0_transcript_segments",
        &[
            "end_ms",
            "ordinal",
            "segment_id",
            "speaker_id",
            "start_ms",
            "text",
            "transcript_version_id",
        ],
    )?;
    require_columns(
        connection,
        "pod0_evidence_generations",
        &[
            "artifact_schema_version",
            "chunk_policy_version",
            "episode_id",
            "generation_id",
            "integrity_digest",
            "overlap_per_mille",
            "snap_tolerance_per_mille",
            "span_count",
            "staged_at_ms",
            "state",
            "target_tokens",
            "transcript_version_id",
            "verified_at_ms",
        ],
    )?;
    require_columns(
        connection,
        "pod0_evidence_spans",
        &[
            "chunk_policy_version",
            "end_ms",
            "end_segment_ordinal_exclusive",
            "first_segment_id",
            "generation_id",
            "last_segment_id",
            "sort_order",
            "span_id",
            "speaker_id",
            "start_ms",
            "start_segment_ordinal",
            "text",
        ],
    )?;
    require_columns(
        connection,
        "pod0_evidence_selection",
        &[
            "episode_id",
            "generation_id",
            "generation_state",
            "selected_at_ms",
        ],
    )?;
    require_columns(
        connection,
        "pod0_evidence_commands",
        &[
            "command_fingerprint",
            "command_id",
            "completed_at_ms",
            "episode_id",
            "generation_id",
            "operation_code",
            "previous_generation_id",
            "result_code",
        ],
    )?;
    Ok(())
}
