use rusqlite::Connection;

use crate::StorageError;
use crate::schema_introspection::require_columns;

pub(crate) fn validate_download_workflow_schema(
    connection: &Connection,
) -> Result<(), StorageError> {
    require_columns(
        connection,
        "pod0_download_environment",
        &[
            "available_capacity_bytes",
            "network_code",
            "network_wire_code",
            "observed_at_ms",
            "singleton",
        ],
    )?;
    require_columns(
        connection,
        "pod0_download_workflows",
        &[
            "artifact_byte_count",
            "artifact_digest",
            "artifact_key",
            "attempt",
            "attempt_id",
            "cancellation_id",
            "command_id",
            "created_at_ms",
            "deadline_at_ms",
            "desired_state",
            "enclosure_url",
            "episode_id",
            "external_task_key",
            "failure_code",
            "failure_detail",
            "failure_retryable",
            "input_version",
            "intent_id",
            "issued_revision",
            "not_before_ms",
            "origin_code",
            "origin_wire_code",
            "request_id",
            "resume_key",
            "stage",
            "updated_at_ms",
            "workflow_revision",
        ],
    )?;
    require_columns(
        connection,
        "pod0_download_attempts",
        &[
            "attempt",
            "attempt_id",
            "created_at_ms",
            "episode_id",
            "external_task_key",
            "failure_code",
            "failure_detail",
            "intent_id",
            "request_id",
            "resume_key",
            "staged_byte_count",
            "staged_digest",
            "staged_path",
            "state",
            "updated_at_ms",
        ],
    )?;
    require_columns(
        connection,
        "pod0_download_host_requests",
        &[
            "artifact_key",
            "attempt_id",
            "cancellation_id",
            "command_id",
            "created_at_ms",
            "deadline_at_ms",
            "enclosure_url",
            "episode_id",
            "external_task_key",
            "input_version",
            "intent_id",
            "issued_revision",
            "kind",
            "last_sequence_number",
            "request_id",
            "resume_key",
            "state",
            "updated_at_ms",
        ],
    )
}
