use rusqlite::Connection;

use crate::StorageError;
use crate::schema_introspection::require_columns;

pub(crate) fn validate_transcripts_schema(connection: &Connection) -> Result<(), StorageError> {
    require_columns(
        connection,
        "pod0_transcript_imports",
        &[
            "backup_database_byte_count",
            "backup_database_digest",
            "committed_at_ms",
            "diagnostic_code",
            "discarded_at_ms",
            "import_id",
            "selected_count",
            "source_database_digest",
            "source_generation",
            "source_kind",
            "source_schema_version",
            "source_selection_digest",
            "staged_at_ms",
            "state",
            "target_revision",
            "verified_at_ms",
        ],
    )?;
    require_columns(
        connection,
        "pod0_transcript_artifacts",
        &[
            "artifact_id",
            "created_at_ms",
            "episode_id",
            "generated_at_ms",
            "integrity_digest",
            "language",
            "schema_version",
            "segment_count",
            "source_import_id",
            "speaker_count",
            "transcript_version_id",
            "word_count",
        ],
    )?;
    require_columns(
        connection,
        "pod0_transcript_speakers",
        &[
            "artifact_id",
            "display_name",
            "label",
            "ordinal",
            "speaker_id",
        ],
    )?;
    require_columns(
        connection,
        "pod0_transcript_artifact_segments",
        &[
            "artifact_id",
            "ordinal",
            "raw_text",
            "segment_id",
            "transcript_version_id",
            "word_count",
        ],
    )?;
    require_columns(
        connection,
        "pod0_transcript_words",
        &[
            "artifact_id",
            "end_ms",
            "ordinal",
            "segment_id",
            "start_ms",
            "text",
            "transcript_version_id",
        ],
    )?;
    require_columns(
        connection,
        "pod0_transcript_import_entries",
        &[
            "artifact_id",
            "backup_file_byte_count",
            "backup_file_digest",
            "episode_id",
            "import_id",
            "legacy_input_version",
            "legacy_integrity",
            "legacy_origin",
            "legacy_output_version",
            "legacy_row_id",
            "legacy_schema_version",
            "legacy_verified_at_ms",
            "selected_file_digest",
            "selected_row_digest",
            "transcript_version_id",
        ],
    )?;
    require_columns(
        connection,
        "pod0_transcript_selection",
        &[
            "artifact_id",
            "episode_id",
            "selected_at_ms",
            "selection_revision",
            "source_import_id",
            "transcript_version_id",
        ],
    )?;
    require_columns(
        connection,
        "pod0_transcript_state",
        &["collection_revision", "singleton", "source_import_id"],
    )?;
    require_columns(
        connection,
        "pod0_transcript_commands",
        &[
            "already_selected",
            "artifact_id",
            "command_fingerprint",
            "command_id",
            "completed_at_ms",
            "episode_id",
            "expected_selection_revision",
            "operation_code",
            "previous_artifact_id",
            "resulting_selection_revision",
            "transcript_version_id",
        ],
    )?;
    Ok(())
}
