use rusqlite::Connection;

use crate::StorageError;
use crate::schema_introspection::require_columns;

pub(crate) fn validate_chapters_schema(connection: &Connection) -> Result<(), StorageError> {
    require_columns(
        connection,
        "pod0_chapter_imports",
        &[
            "ad_span_count",
            "artifact_count",
            "backup_database_byte_count",
            "backup_database_digest",
            "backup_file_byte_count",
            "backup_file_count",
            "blocked_count",
            "chapter_count",
            "command_fingerprint",
            "diagnostic_code",
            "discarded_at_ms",
            "evidence_count",
            "import_id",
            "imported_at_ms",
            "selected_count",
            "source_byte_count",
            "source_database_digest",
            "source_generation",
            "source_identity",
            "source_kind",
            "source_selection_digest",
            "staged_at_ms",
            "state",
            "target_revision",
            "verified_at_ms",
        ],
    )?;
    require_columns(
        connection,
        "pod0_chapter_artifacts",
        &[
            "ad_span_count",
            "ad_span_evaluation_code",
            "artifact_id",
            "chapter_count",
            "content_digest",
            "created_at_ms",
            "duration_ms",
            "episode_id",
            "generated_at_ms",
            "integrity_digest",
            "legacy_generated_at_was_unknown",
            "legacy_original_origin",
            "legacy_source_code",
            "model",
            "podcast_id",
            "policy_version",
            "provider",
            "schema_version",
            "source_code",
            "source_import_id",
            "source_payload_digest",
            "source_revision",
            "transcript_content_digest",
            "transcript_version_id",
        ],
    )?;
    require_columns(
        connection,
        "pod0_chapter_items",
        &[
            "artifact_id",
            "chapter_id",
            "end_ms",
            "image_url",
            "include_in_table_of_contents",
            "link_url",
            "ordinal",
            "source_episode_id",
            "start_ms",
            "summary",
            "title",
        ],
    )?;
    require_columns(
        connection,
        "pod0_ad_spans",
        &[
            "ad_span_id",
            "artifact_id",
            "end_ms",
            "kind_code",
            "ordinal",
            "start_ms",
        ],
    )?;
    require_columns(
        connection,
        "pod0_chapter_import_entries",
        &[
            "artifact_id",
            "backup_file_byte_count",
            "backup_file_digest",
            "diagnostic_code",
            "entry_id",
            "episode_id",
            "evidence_kind",
            "import_id",
            "importer_selected",
            "legacy_selected",
            "raw_byte_count",
            "raw_digest",
            "podcast_id",
            "source_file_byte_count",
            "source_file_digest",
            "source_file_path",
            "source_input_version",
            "source_integrity",
            "source_kind",
            "source_origin",
            "source_output_version",
            "source_row_digest",
            "source_row_id",
            "source_schema_version",
            "source_subject",
            "source_verified_at_ms",
            "validation_state",
        ],
    )?;
    require_columns(
        connection,
        "pod0_chapter_selections",
        &[
            "artifact_id",
            "episode_id",
            "selected_at_ms",
            "selection_revision",
            "source_import_id",
        ],
    )?;
    require_columns(
        connection,
        "pod0_chapter_import_chapter_evidence",
        &[
            "chapter_id",
            "entry_id",
            "import_id",
            "legacy_id",
            "legacy_is_ai_generated",
            "ordinal",
        ],
    )?;
    require_columns(
        connection,
        "pod0_chapter_import_ad_evidence",
        &[
            "ad_span_id",
            "entry_id",
            "import_id",
            "legacy_id",
            "ordinal",
        ],
    )?;
    require_columns(
        connection,
        "pod0_chapter_state",
        &[
            "authority_active",
            "authority_import_id",
            "collection_revision",
            "singleton",
        ],
    )?;
    let inactive_rows: u32 = connection
        .query_row(
            "SELECT COUNT(*) FROM pod0_chapter_state \
             WHERE singleton=1 AND authority_active=0 AND authority_import_id IS NULL",
            [],
            |row| row.get(0),
        )
        .map_err(|error| StorageError::sqlite("validate chapter authority state", error))?;
    if inactive_rows != 1 {
        return Err(StorageError::CorruptSchema {
            detail: "chapter authority must remain inactive",
        });
    }
    Ok(())
}
