fun qualifySchemaFixture(fixture: Map<String, String>) {
    check(fixture["fixture_version"] == "1")
    check(fixture["schema_component"] == "kernel")
    check(fixture["stored_version"]?.toUInt() == 2u)
    check(fixture["supported_min"]?.toUInt() == 0u)
    check(fixture["supported_max"]?.toUInt() == 12u)
    check(fixture["access_mode"] == "migration_only")
    check(fixture["migration_state"] == "required")
    check(fixture["target_version"]?.toUInt() == 12u)
    check(fixture["store_id_high"]?.toULong() == 10UL)
    check(fixture["store_id_low"]?.toULong() == 11UL)
    check(fixture["command_id_high"]?.toULong() == 1UL)
    check(fixture["command_id_low"]?.toULong() == 2UL)
    check(fixture["state_revision"]?.toULong() == 42UL)
    check(fixture["operation_stage"] == "failed")
    check(fixture["error_kind"] == "unsupported")
    check(fixture["error_wire_code"]?.toUInt() == 9001u)
    check(fixture["optional_safe_detail"] == "null")
}
