import Foundation
import Pod0Core
import XCTest
@testable import Podcastr

final class SharedLibraryGeneratedAudioMappingTests: XCTestCase {
    func testRustGeneratedAudioProvenanceProjectsTheConversationSource() throws {
        let conversationID = ConversationId(high: 3, low: 4)
        let record = EpisodeRecord(
            episodeId: EpisodeId(high: 1, low: 2),
            podcastId: PodcastId(high: 5, low: 6),
            publisherGuid: "file:///private/agent/briefing.mp3",
            title: "Briefing",
            description: "Generated by Pod0 Agent.",
            publishedAt: UnixTimestampMilliseconds(value: 1_900_000_000_000),
            durationMilliseconds: nil,
            enclosureUrl: "file:///private/agent/briefing.mp3",
            enclosureMimeType: "audio/mpeg",
            imageUrl: nil,
            feedMetadata: EpisodeFeedMetadata(
                publisherTranscript: nil,
                chaptersUrl: nil,
                persons: [],
                soundBites: []
            ),
            listening: EpisodeListeningState(
                resumePositionMilliseconds: 0,
                completion: .inProgress
            ),
            isStarred: false,
            download: .unavailable,
            transcript: .unavailable,
            generatedAudio: GeneratedAudioArtifactProvenance(
                artifactId: GeneratedArtifactId(high: 7, low: 8),
                conversationId: conversationID,
                turnId: AgentTurnId(high: 9, low: 10),
                proposalId: AgentProposalId(high: 11, low: 12),
                commitId: AgentCommitId(high: 13, low: 14),
                mediaContentDigest: ContentDigest(
                    word0: 15,
                    word1: 16,
                    word2: 17,
                    word3: 18
                ),
                scriptContentDigest: ContentDigest(
                    word0: 19,
                    word1: 20,
                    word2: 21,
                    word3: 22
                ),
                mediaByteCount: 1_024,
                voiceId: "calm",
                modelReference: "openrouter/test",
                committedAt: UnixTimestampMilliseconds(value: 1_900_000_000_000)
            )
        )

        let episode = try XCTUnwrap(record.swiftValue(
            preserving: nil,
            chapters: nil,
            downloadState: .notDownloaded
        ))

        XCTAssertEqual(
            episode.generationSource,
            .inAppChat(conversationID: try XCTUnwrap(conversationID.uuid))
        )
    }
}
